#!/usr/bin/env bash
INPUT_FILE=$1
START_LINE=`head -n1 $INPUT_FILE`
PATTERN="^\[(allset)-[[:digit:]]{4}] [A-Z].+"
if ! [[ "$START_LINE" =~ $PATTERN ]]; then
  echo "Bad commit message, see example: [allset-0000] Commit message"
  exit 1
fi