#!/usr/bin/env bash
STAGED_FILES=$(git diff --cached --name-only --diff-filter=ACM | grep -E '\.(js|jsx|ts|tsx)$')

if [[ "$STAGED_FILES" = "" ]]; then
  exit 0
fi

echo Validating Javascript

for FILE in $STAGED_FILES
do
  node_modules/.bin/eslint -c config/.eslintrc --ignore-path config/.eslintignore "$FILE"

  if [[ "$?" == 0 ]]; then
    echo Javascript validation completed!
  else
    exit 1
  fi
done

exit $?