#!/usr/bin/env bash

branchPath=$(git symbolic-ref -q HEAD) #Somthing like refs/heads/myBranchName
branchName=${branchPath##*/}      #Get text behind the last / of the branch path

regex="(allset-[0-9]*)"

# check that this is a regular commit
if [ "$COMMIT_SOURCE" = "message" ] || [ -z "$COMMIT_SOURCE" ]
then
    if [[ $branchName =~ $regex ]]
    then
        # Get the captured portion of the branch name.
        jiraTicketName="${BASH_REMATCH[1]}"
        commitMessage=`cat $1`
        commitMessageCamelCase=`echo ${commitMessage:0:1} | tr  '[a-z]' '[A-Z]'`${commitMessage:1}

        sed -i.bak -e "1s/^/[$jiraTicketName] /" $1
    fi
fi