#!/usr/bin/env bash
INPUT_FILE=$1
COMMIT_MSG=`head -n1 $INPUT_FILE`
PATTERN="^\[(FEATURE-)?ALLSET-[[:digit:]]{4}] [A-Z].+"

if ! [[ "$COMMIT_MSG" =~ $PATTERN ]]; then
  echo "Bad commit message: $COMMIT_MSG, see example: [ALLSET-0000] Commit message or [FEATURE-ALLSET-0000] Commit message"
  exit 1
fi