#!/usr/bin/env bash
INPUT_FILE=$1
COMMIT_MSG=`head -n1 $INPUT_FILE`
PATTERN="^\[allset-[[:digit:]]+] [A-Z].+"

if ! [[ "$COMMIT_MSG" =~ $PATTERN ]]; then
  echo `tput setaf 1`"Bad commit message: $COMMIT_MSG, see example: [allset-0000] Commit message"`tput sgr0`
  exit 1
fi