#!/usr/bin/env bash
BRANCH_PATH=$(git symbolic-ref -q HEAD)
BRANCH_NAME=${BRANCH_PATH##*/}
PATTERN="^((epic-)?allset-[[:digit:]]+)|(main)"

if ! [[ "$BRANCH_NAME" =~ $PATTERN ]]; then
  echo "Bad branch name: $BRANCH_NAME, see example: allset-0000,epic-allset-0000"

  git checkout main
  git branch -D $BRANCH_NAME
  exit 1
fi