#!/usr/bin/env bash
STAGED_FILES=$(git diff --cached --name-only --diff-filter=ACM | grep -E '\.(js|jsx|ts|tsx)$')

if [ $NO_CHECK ]; then
  exit 0
fi

if [[ "$STAGED_FILES" = "" ]]; then
  exit 0
fi

echo `tput setaf 2`Validating Javascript`tput sgr0`

for FILE in $STAGED_FILES
do
  node_modules/.bin/eslint -c config/.eslintrc --ignore-path config/.eslintignore "$FILE"

  if [[ "$?" == 0 ]]; then
    echo `tput setaf 2`Javascript validation completed!`tput sgr0`
  else
    exit 1
  fi
done

exit $?