#!/usr/bin/env bash
BRANCH_PATH=$(git symbolic-ref -q HEAD)
BRANCH_NAME=${BRANCH_PATH##*/}
STAGED_FILES=$(git diff --cached --name-only --diff-filter=ACM | grep -E '\.(js|jsx|ts|tsx)$')
REBASE_REGEX="(^$)"

echo "BRANCH_NAME: $BRANCH_NAME"

if [ $NO_CHECK ]; then
  exit 0
fi

if [[ "$STAGED_FILES" = "" ]]; then
  exit 0
fi

echo `tput setaf 2`Validating Javascript`tput sgr0`

LINT_ERROR=false

for FILE in $STAGED_FILES
do
  node_modules/.bin/eslint -c config/.eslintrc --ignore-path config/.eslintignore "$FILE"

  if ! [[ "$?" == 0 ]]; then
    LINT_ERROR=true
  fi
done

if [[ $LINT_ERROR == true ]]; then
  exit 1
else
  echo `tput setaf 2`Javascript validation completed!`tput sgr0`
fi

exit $?