#!/usr/bin/env bash

BRANCH_PATH=$(git symbolic-ref -q HEAD)
BRANCH_NAME=${BRANCH_PATH##*/}
EXCLUDE_REGEX="(main)"

if [ $NO_CHECK ]; then
  exit 0
fi

if [ "$COMMIT_SOURCE" = "message" ] || [ -z "$COMMIT_SOURCE" ]; then
  if ! [[ "$BRANCH_NAME" =~ $EXCLUDE_REGEX ]]; then
    commitMessage=`cat $1`
    firstLetterCaps=`echo ${commitMessage:0:1} | tr  '[a-z]' '[A-Z]'`

    sed -i "" "s/${commitMessage:0:1}/[$BRANCH_NAME] $firstLetterCaps/" $1
  fi
fi