#!/usr/bin/env bash
BRANCH_PATH=$(git symbolic-ref -q HEAD)
BRANCH_NAME=${BRANCH_PATH##*/}
PATTERN="^\[allset-[[:digit:]]+]"
EXCLUDE_REGEX="(main)"
COMMIT_MSG=`cat $1`
FIRST_LETTER_CAPS=`echo ${COMMIT_MSG:0:1} | tr  '[a-z]' '[A-Z]'`

if [ $NO_CHECK ]; then
  exit 0
fi

if [ "$COMMIT_SOURCE" = "message" ] || [ -z "$COMMIT_SOURCE" ]; then
  if ! [[ "$BRANCH_NAME" =~ $EXCLUDE_REGEX ]]; then
    if ! [[ "$COMMIT_MSG" =~ $PATTERN ]]; then
      sed -i "" "s/${COMMIT_MSG:0:1}/[$BRANCH_NAME] $FIRST_LETTER_CAPS/" $1
    fi
  fi
fi