# NOTE:(Git action types) https://frontside.com/blog/2020-05-26-github-actions-pull_request/

name: 'Checking PR Title'
on:
  pull_request_target:
    types:
      - opened
      - edited
      - reopened

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: allset-inc/gitactions@v1.46
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CHECK: 'checkPR'
          JIRA_HOST_URL: 'https://allset.atlassian.net'
          JIRA_PROJECT_NAME: 'allset'
