name: 'Cheking PR Title'
on:
  pull_request_target:
    types:
      - opened
      - edited
      - synchronize

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: allset-inc/gitactions@v1.34
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CHECK: 'title'
