name: 'Updating PR Decription'
on:
  pull_request_target:
    types:
      - opened
      - synchronize

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: allset-web-app/githooks@v1.23
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CHECK: 'desc'
