name: 'Updating PR Decription'
on:
  pull_request_target:
    types:
      - opened
      - synchronize

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: allset-inc/gitactions@v1.43
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CHECK: 'updatePR'
          JIRA_HOST_URL: 'https://logichub.atlassian.net'
          JIRA_PROJECT_NAME: 'allset'
